=== msama/contextnotifier/xml/ActivitySchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ucl.cs.ac.uk/ContextNotifier/ActivitySchema" xmlns:tns="http://www.ucl.cs.ac.uk/ContextNotifier/ActivitySchema" elementFormDefault="qualified">

    <complexType name="ConstraintNode">
    	<sequence>
    		<element name="Param" type="tns:Param"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="Value" type="string" use="required"></attribute>
    	<attribute name="Type" type="string" use="required"></attribute>
    	<attribute name="Handler" type="string" use="required"></attribute>
    	<attribute name="Redifined" type="boolean"></attribute>
    </complexType>


    <complexType name="OrConstraintNode">
    	<sequence maxOccurs="unbounded" minOccurs="2">
    		<choice minOccurs="1" maxOccurs="1">
    			<element name="ConstraintNode"
    				type="tns:ConstraintNode">
    			</element>
    			<element name="OrConstraintNode" type="tns:OrConstraintNode"></element>
    			<element name="AndConstraintNode" type="tns:AndConstraintNode"></element>
    			<element name="NotConstraintNode" type="tns:NotConstraintNode"></element>
    		</choice>
    	</sequence>
    </complexType>

    <complexType name="AndConstraintNode">
    	<sequence maxOccurs="unbounded" minOccurs="2">
    		<choice minOccurs="1" maxOccurs="1">
    			<element name="ConstraintNode"
    				type="tns:ConstraintNode">
    			</element>
    			<element name="OrConstraintNode" type="tns:OrConstraintNode"></element>
    			<element name="AndConstraintNode" type="tns:AndConstraintNode"></element>
    			<element name="NotConstraintNode" type="tns:NotConstraintNode"></element>
    		</choice>
    	</sequence>
    </complexType>

    <complexType name="Rule">
    	<sequence>
    		<element name="NotificationTree" type="tns:ConstraintTree"
    			minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="ActivationTree" type="tns:ConstraintTree"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="DeactivationTree" type="tns:ConstraintTree"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="Notification" type="tns:Notification" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="Name" type="string" use="required"></attribute>
    	<attribute name="OccurrenceMsec" type="int" use="required"></attribute>
    </complexType>

    <complexType name="Activity">
    	<sequence maxOccurs="unbounded" minOccurs="0">
    		<element name="Rule" type="tns:Rule"></element>
    	</sequence>
    	<attribute name="Name" type="string"></attribute>
    	<attribute name="Description" type="string"></attribute>
    	<attribute name="Date" type="int"></attribute>
    	<attribute name="Sample" type="boolean" use="optional"></attribute>
    </complexType>

    <element name="Activity" type="tns:Activity"></element>

    <complexType name="Notification">
    	<sequence minOccurs="0" maxOccurs="unbounded">
    		<element name="Param" type="tns:Param"></element>
    	</sequence>
    	<attribute name="Notifier" type="string" use="required"></attribute>
    	<attribute name="RemoveActivity" type="boolean"
    		use="required">
    	</attribute>
    	<attribute name="RemoveRule" type="boolean" use="required"></attribute>
    </complexType>

    <complexType name="Param">
    	<attribute name="Name" type="string" use="required"></attribute>
    	<attribute name="Value" type="string" use="required"></attribute>
    </complexType>

    <complexType name="NotConstraintNode">
    	<choice minOccurs="1" maxOccurs="1">
    			<element name="ConstraintNode"
    				type="tns:ConstraintNode">
    			</element>
    			<element name="OrConstraintNode" type="tns:OrConstraintNode"></element>
    			<element name="AndConstraintNode" type="tns:AndConstraintNode"></element>
    			<element name="NotConstraintNode" type="tns:NotConstraintNode"></element>
    		</choice>
    </complexType>

    <complexType name="ConstraintTree">
    		<choice minOccurs="1" maxOccurs="1">
    			<element name="ConstraintNode"
    				type="tns:ConstraintNode">
    			</element>
    			<element name="AndConstraintNode"
    				type="tns:AndConstraintNode">
    			</element>
    			<element name="OrConstraintNode"
    				type="tns:OrConstraintNode">
    			</element>
    			<element name="NotConstraintNode"
    				type="tns:NotConstraintNode">
    			</element>
    		</choice>
    </complexType>
</schema>

=== msama/contextnotifier/xml/SampleActivity2.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Activity 
	xmlns:tns="http://www.ucl.cs.ac.uk/ContextNotifier/ActivitySchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.ucl.cs.ac.uk/ContextNotifier/ActivitySchema ActivitySchema.xsd "
	Name="Sample2" 
	Description="This sample loads a TimeHandler." 
	Date="0"
	Sample="true">
  <tns:Rule Name="Sample2_Rule0" OccurrenceMsec="0">
    <tns:NotificationTree>
    	<tns:ConstraintNode Handler="TimeHandler" Type="Greater" Value="100000000" Redifined="false"/>
    </tns:NotificationTree>
    <tns:ActivationTree>
    	<tns:ConstraintNode Handler="TimeHandler" Type="Greater" Value="20000" Redifined="false"/>
    </tns:ActivationTree>
    <tns:Notification RemoveActivity="true" RemoveRule="false" Notifier="VibrationNotifier">
    	<tns:Param Name="Message" Value="TimeSample"/>
    </tns:Notification>
  </tns:Rule>
</tns:Activity>

=== msama/contextnotifier/xml/SampleActivity0.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Activity
	xmlns:tns="http://www.ucl.cs.ac.uk/ContextNotifier/ActivitySchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ucl.cs.ac.uk/ContextNotifier/ActivitySchema ActivitySchema.xsd "
	Name="Sample0"
	Description="Start a vibration when specific BT devices are in the area."
	Date="0" Sample="true">
	<tns:Rule Name="BT_Blackhole" OccurrenceMsec="10000">
		<tns:NotificationTree>
			<tns:ConstraintNode Handler="BlueToothFinder" Type="Equals"
				Value="Blackhole" Redifined="false" />
		</tns:NotificationTree>
		<tns:Notification RemoveActivity="true" RemoveRule="false" Notifier="VibrationNotifier">
			<tns:Param Name="Message" Value="Found BlackHole"/>
		</tns:Notification>
	</tns:Rule>
	<tns:Rule Name="BT_MyComputer" OccurrenceMsec="10000">
		<tns:NotificationTree>
			<tns:ConstraintNode Handler="BlueToothFinder" Type="Equals"
				Value="MyComputer" Redifined="false" />
		</tns:NotificationTree>
		<tns:Notification RemoveActivity="false" RemoveRule="false" Notifier="VibrationNotifier">
			<tns:Param Name="Message" Value="Found MyComputer"/>
		</tns:Notification>
	</tns:Rule>
</tns:Activity>

=== msama/contextnotifier/xml/Meeting.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Activity Date="0"
	Description="A really important meeting that you should attend in Boss office."
	Name="Meeting" Sample="true"
	xmlns:tns="http://www.ucl.cs.ac.uk/ContextNotifier/ActivitySchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ucl.cs.ac.uk/ContextNotifier/ActivitySchema ActivitySchema.xsd ">
	<tns:Rule Name="Long term Reminder" OccurrenceMsec="150000">
		<tns:NotificationTree>
			<tns:NotConstraintNode>
				<tns:OrConstraintNode>
					<tns:OrConstraintNode>
						<tns:ConstraintNode Handler="BlueToothFinder"
							Type="Equals" Value="MyBossComputer" Redifined="false" />
						<tns:ConstraintNode Handler="GPSLocation"
							Type="Lesser" Value="MyBossOffice" Redifined="true">
							<tns:Param Name="Latitude"
								Value="51:31:23.75" />
							<tns:Param Name="Longitude" Value="7:56.99" />
							<tns:Param Name="Altitude" Value="20" />
							<tns:Param Name="Radius" Value="50" />
						</tns:ConstraintNode>
					</tns:OrConstraintNode>
					<tns:ConstraintNode Handler="BlueToothFinder"
						Type="Equals" Value="MyBossMobile" Redifined="false" />
					<tns:AndConstraintNode>
						<tns:ConstraintNode Handler="GPSLocation"
							Type="Lesser" Value="MyOffice" Redifined="true">
							<tns:Param Name="Latitude"
								Value="51:31:23.75" />
							<tns:Param Name="Longitude" Value="7:56.99" />
							<tns:Param Name="Altitude" Value="20" />
							<tns:Param Name="Radius" Value="50" />
						</tns:ConstraintNode>
						<tns:ConstraintNode Handler="BlueToothFinder"
							Type="Equals" Value="MyComputer" Redifined="false" />
					</tns:AndConstraintNode>
				</tns:OrConstraintNode>
			</tns:NotConstraintNode>
		</tns:NotificationTree>
		<tns:ActivationTree>
			<tns:AndConstraintNode>
				<tns:OrConstraintNode>
					<tns:ConstraintNode Handler="GPSLocation"
						Type="Greater" Value="MyBossOffice" Redifined="true">
						<tns:Param Name="Latitude" Value="51:31:23.75" />
						<tns:Param Name="Longitude" Value="7:56.99" />
						<tns:Param Name="Altitude" Value="20" />
						<tns:Param Name="Radius" Value="5000" />
					</tns:ConstraintNode>
					<tns:AndConstraintNode>
						<tns:ConstraintNode Value="3600000"
							Type="Greater" Handler="TimeHandler">
						</tns:ConstraintNode>
						<tns:ConstraintNode Handler="GPSLocation"
							Type="Greater" Value="MyBossOffice" Redifined="true">
							<tns:Param Name="Latitude"
								Value="51:31:23.75" />
							<tns:Param Name="Longitude" Value="7:56.99" />
							<tns:Param Name="Altitude" Value="20" />
							<tns:Param Name="Radius" Value="2500" />
						</tns:ConstraintNode>
					</tns:AndConstraintNode>
					<tns:ConstraintNode Value="6900000" Type="Greater"
						Handler="TimeHandler">
					</tns:ConstraintNode>
				</tns:OrConstraintNode>
				<tns:ConstraintNode Value="8700000" Type="Lesser"
					Handler="TimeHandler"/>
			</tns:AndConstraintNode>
		</tns:ActivationTree>
		<tns:DeactivationTree>
			<tns:ConstraintNode Value="8700000" Type="Greater"
				Handler="TimeHandler">
			</tns:ConstraintNode>
		</tns:DeactivationTree>
		<tns:Notification RemoveActivity="false" RemoveRule="false"
			Notifier="RingtoneNotifier">
			<tns:Param Name="Message"
				Value="You seam to be really far from the meeting place. Try to go closer to the the place in wich the meeting will occur." />
		</tns:Notification>
	</tns:Rule>
	<tns:Rule Name="5' Reminder" OccurrenceMsec="0">
		<tns:NotificationTree>
			<tns:NotConstraintNode>
				<tns:OrConstraintNode>
					<tns:AndConstraintNode>
						<tns:ConstraintNode Handler="BlueToothFinder"
							Type="Equals" Value="MyBossComputer" Redifined="false" />
						<tns:ConstraintNode Handler="GPSLocation"
							Type="Lesser" Value="MyBossOffice" Redifined="true">
							<tns:Param Name="Latitude"
								Value="51:31:23.75" />
							<tns:Param Name="Longitude" Value="7:56.99" />
							<tns:Param Name="Altitude" Value="20" />
							<tns:Param Name="Radius" Value="50" />
						</tns:ConstraintNode>
					</tns:AndConstraintNode>
					<tns:ConstraintNode Handler="BlueToothFinder"
						Type="Equals" Value="MyBossMobile" Redifined="false" />
				</tns:OrConstraintNode>
			</tns:NotConstraintNode>

		</tns:NotificationTree>
		<tns:ActivationTree>
			<tns:ConstraintNode Value="8700000" Type="Greater"
				Handler="TimeHandler">
			</tns:ConstraintNode>
		</tns:ActivationTree>
		<tns:DeactivationTree>
			<tns:ConstraintNode Value="9000000" Type="Greater"
				Handler="TimeHandler">
			</tns:ConstraintNode>
		</tns:DeactivationTree>
		<tns:Notification RemoveActivity="true" RemoveRule="false"
			Notifier="VibrationNotifier">
			<tns:Param Name="Message"
				Value="The meeting will start in 5 minutes. Pack your staff and go to the meeting place." />
		</tns:Notification>
	</tns:Rule>
	<tns:Rule Name="Presentation File" OccurrenceMsec="300000">
		<tns:NotificationTree>
			<tns:ConstraintNode Value="file:///E:/Presentation.ppt"
				Type="NotEquals" Handler="FileSystemHandler" Redifined="false">
			</tns:ConstraintNode>
		</tns:NotificationTree>
		<tns:Notification RemoveActivity="false" RemoveRule="false"
			Notifier="RingtoneNotifier">
			<tns:Param Name="Message"
				Value="The presentation file is missing. Be sure that u have it with u." />
		</tns:Notification>
	</tns:Rule>
</tns:Activity>

=== msama/contextnotifier/xml/SampleActivity1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Activity 
	xmlns:tns="http://www.ucl.cs.ac.uk/ContextNotifier/ActivitySchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.ucl.cs.ac.uk/ContextNotifier/ActivitySchema ActivitySchema.xsd "
	Name="Sample1" 
	Description="This sample loads ContextHandlers and dispose them in order to see if they are garbagecollected properly." 
	Date="0"
	Sample="true">
  <tns:Rule Name="Sample1_Rule0" OccurrenceMsec="0">
    <tns:NotificationTree>
    	<tns:OrConstraintNode>
    	<tns:ConstraintNode Handler="BlueToothFinder" Type="NotEquals" Value="BT" Redifined="false"/>
    	<tns:ConstraintNode Handler="TimeHandler" Type="Lesser" Value="0" Redifined="false"/>
    	<tns:ConstraintNode Handler="GPSLocation" Type="NotEquals" Value="AnyPlace" Redifined="false"/>
    </tns:OrConstraintNode>
    </tns:NotificationTree>
    <tns:ActivationTree>
    	<tns:ConstraintNode Value="10000" Type="Greater" Handler="TimeHandler"></tns:ConstraintNode>
    </tns:ActivationTree>
    <tns:DeactivationTree>
    	<tns:ConstraintNode Value="50000" Type="Greater" Handler="TimeHandler"></tns:ConstraintNode>	
    </tns:DeactivationTree>
    <tns:Notification RemoveActivity="true" RemoveRule="false" Notifier="VibrationNotifier">
    <tns:Param Name="Message" Value="All the handler will be disposed."/>
    </tns:Notification>
  </tns:Rule>
</tns:Activity>
